// i used ai to generate this cuz im a lazy pos
export const ICONS = {
  // ── Files & Folders ──────────────────────────────────────────
  ICON_FOLDER:          '󰉋',
  ICON_FOLDER_OPEN:     '󰝰',
  ICON_FILE:            '󰈔',
  ICON_FILE_TEXT:       '󰈙',
  ICON_FILE_CODE:       '󰈮',
  ICON_FILE_JSON:       '󰘦',
  ICON_FILE_PDF:        '󰈦',
  ICON_FILE_IMAGE:      '󰈟',
  ICON_FILE_VIDEO:      '󰈫',
  ICON_FILE_AUDIO:      '󰈣',
  ICON_FILE_ZIP:        '󰛫',
  ICON_TRASH:           '󰩺',
  ICON_COPY:            '󰆏',
  ICON_PASTE:           '󰆒',
  ICON_SAVE:            '󰆓',
  ICON_DOWNLOAD:        '󰇚',
  ICON_UPLOAD:          '󰇹',

  // ── Git ──────────────────────────────────────────────────────
  ICON_GIT:             '󰊢',
  ICON_GIT_BRANCH:      '󰘬',
  ICON_GIT_COMMIT:      '󰜘',
  ICON_GIT_MERGE:       '󰘭',
  ICON_GIT_PR:          '󰘮',
  ICON_GIT_DIFF:        '󰦙',
  ICON_GIT_STASH:       '󰜘',
  ICON_GITHUB:          '󰊤',
  ICON_GITLAB:          '󰮠',

  // ── Languages & Runtimes ────────────────────────────────────
  ICON_NODE:            '󰎙',
  ICON_NPM:             '󰎙',
  ICON_YARN:            '󰆸',
  ICON_BUN:             '󰟳',
  ICON_PYTHON:          '󰌠',
  ICON_RUST:            '󱘗',
  ICON_GO:              '󰟓',
  ICON_JAVA:            '󰬷',
  ICON_LUA:             '󰢱',
  ICON_HTML:            '󰌝',
  ICON_CSS:             '󰌜',
  ICON_JS:              '󰌞',
  ICON_TS:              '󰛦',
  ICON_JSON:            '󰘦',
  ICON_MARKDOWN:        '󰍔',
  ICON_DOCKER:          '󰡨',
  ICON_KUBERNETES:      '󱃾',
  ICON_TERRAFORM:       '󱁢',

  // ── Apps & Tools ────────────────────────────────────────────
  ICON_VSCODE:          '󰨞',
  ICON_VIM:             '󰕷',
  ICON_NEOVIM:          '󰕷',
  ICON_TERMINAL:        '',
  ICON_BASH:            '',
  ICON_ZSH:             '',
  ICON_FISH:            '󰈺',
  ICON_SSH:             '󰣀',
  ICON_TMUX:            '󱂬',
  ICON_BROWSER:         '󰖟',
  ICON_FIREFOX:         '󰈹',
  ICON_CHROME:          '󰊯',

  // ── System ──────────────────────────────────────────────────
  ICON_LINUX:           '󰌽',
  ICON_ARCH:            '󰣇',
  ICON_UBUNTU:          '󰕈',
  ICON_DEBIAN:          '󰣚',
  ICON_APPLE:           '󰀵',
  ICON_WINDOWS:         '󰍲',
  ICON_CPU:             '󰻟',
  ICON_RAM:             '󰍛',
  ICON_DISK:            '󰋊',
  ICON_WIFI:            '󰤨',
  ICON_ETHERNET:        '󰈀',
  ICON_BLUETOOTH:       '󰂯',
  ICON_BATTERY:         '󰁹',
  ICON_BATTERY_LOW:     '󰁺',
  ICON_POWER:           '⏻',

  // ── UI / Status ─────────────────────────────────────────────
  ICON_CHECK:           '󰄬',
  ICON_CROSS:           '󰅙',
  ICON_WARNING:         '󰀪',
  ICON_ERROR:           '󰅚',
  ICON_INFO:            '󰋽',
  ICON_QUESTION:        '󰘥',
  ICON_LOADING:         '󰔟',
  ICON_SEARCH:          '󰍉',
  ICON_SETTINGS:        '󰒓',
  ICON_LOCK:            '󰌾',
  ICON_UNLOCK:          '󰍁',
  ICON_EYE:             '󰈈',
  ICON_BELL:            '󰂚',
  ICON_STAR:            '󰓎',
  ICON_HEART:           '󰣐',
  ICON_BOOKMARK:        '󰃀',
  ICON_TAG:             '󰓹',
  ICON_ARROW_RIGHT:     '󰀂',
  ICON_ARROW_LEFT:      '󰀁',
  ICON_ARROW_UP:        '󰀉',
  ICON_ARROW_DOWN:      '󰀃',
  ICON_CHEVRON_RIGHT:   '󰅂',
  ICON_CHEVRON_LEFT:    '󰅀',
  ICON_PLUS:            '󰐕',
  ICON_MINUS:           '󰐘',
  ICON_DOTS:            '󰇘',

  // ── Time & Date ─────────────────────────────────────────────
  ICON_CLOCK:           '󰔟',
  ICON_CALENDAR:        '󰃰',
  ICON_TIMER:           '󱎫',
  ICON_HOURGLASS:       '󰔛',

  // ── Misc ────────────────────────────────────────────────────
  ICON_PACKAGE:         '󰏗',
  ICON_ROCKET:          '󱓞',
  ICON_FIRE:            '󱠇',
  ICON_SPARKLE:         '󱐋',
  ICON_KEY:             '󰌋',
  ICON_LINK:            '󰌷',
  ICON_CLOUD:           '󰅟',
  ICON_DATABASE:        '󰆼',
  ICON_SERVER:          '󰒋',
  ICON_API:             '󱂛',
  ICON_BUG:             '󰃤',
  ICON_WRENCH:          '󰓾',
  ICON_PAINT:           '󰏘',
  ICON_MUSIC:           '󰝚',
  ICON_USER:            '󰀄',
  ICON_USERS:           '󰀅',
  ICON_HOME:            '󰋜',
  ICON_MAP:             '󰙿',
  ICON_GLOBE:           '󰖟',
  ICON_MAIL:            '󰇮',
  ICON_CHAT:            '󰭹',
};